import { Lang } from "../types";

export const TEXT = {
  en: {
    welcomeTitle: "VitaMyStory",
    welcomeBody: "A simple place to collect the stories that matter.",
    savedDevice: "Stories live on this device.",
    demoNoteTitle: "How this Demo works",
    demoNoteBody: "Your stories are saved safely in your browser. You can export a backup at any time to keep them forever.",
    whoFor: "Who are we writing about?",
    placeholder: "Grandma Elvia",
    justName: "Just a name to start a chapter.",
    continue: "Continue",
    chooseExisting: "Or choose an existing person",
    introTitle: "A sanctuary for memories",
    introBody: (name: string) => 
      `VitaMyStory is where we ensure |||${name}'s||| legacy never fades.\n\nThere is no rush here. Take your time. Capture one story at a time and share them with your family.`,
    startWriting: "Start Writing",
    writeTitle: "Share a memory",
    writeSubtitle: "Don't overthink it. A few sentences is perfect.",
    writePlaceholder: "Start writing here...",
    saveStory: "Save this memory",
    updateStory: "Update memory",
    viewStories: "Read stories",
    viewAllStories: (name: string) => `Read all stories about ${name}`,
    addAnother: "Write another",
    invite: "Invite family", 
    inviteMsg: (name: string) => `I am capturing ${name}'s stories on VitaMyStory. Join me.`,
    milestoneMsg: (name: string) => `Look what I did with ${name}'s story! I just unlocked the Story Keeper badge on VitaMyStory.`,
    shareMilestone: "Share this milestone with your family",
    storyKeeperTooltip: "You are a Story Keeper.",
    badgeModalTitle: "You are a Story Keeper.",
    badgeModalBody: "You have preserved 5 stories. Keep sharing and posting to unlock new features.",
    close: "Close",
    storySaved: "Memory kept.",
    storyShared: "Story shared",
    firstStorySaved: "First memory saved.",
    firstStorySavedPerson: (name: string) => `Your first story about ${name} is safe.`,
    storySavedTitle: "Memory kept.",
    storySavedBody: "This moment is safe.",
    firstStoryTitle: "The first chapter begins.",
    firstStoryBody: "You have started a legacy.",
    secondStoryTitle: "Two stories saved.",
    secondStoryBody: "You are building momentum. Complete 5 stories to unlock special features.",
    storyKeeperTitle: "Story Keeper",
    storyKeeperBody: (name: string) =>
      `You’ve preserved the first chapter of ${name}’s legacy.`, 
    storyKeeperBadge: "Story Keeper",
    storiesOf: "THE STORIES OF",
    storyOf: "THE STORY OF",
    change: "Change",
    emptyHome: "A blank page waiting for memories. Start whenever you’re ready.",
    writeAStory: "Write a story",
    newPerson: "New person",
    resetApp: "Reset app",
    choosePerson: "Select a person",
    noPeople: "No chapters yet.",
    back: "Go back",
    added: "Started",
    demoBanner: "Demo Version: Stories live in your browser cache. Export them to keep them safe.",
    saveBackup: "Export Backup",
    inviteLink: "Invite family (Coming Soon)",
    backupDownloaded: "Backup file downloaded.",
    confirmDeleteTitle: "Delete this memory?",
    confirmDeleteBody: "This action cannot be undone.",
    cancel: "Cancel",
    confirm: "Delete",
    copied: "Copied to clipboard",
    swipeHint: "Swipe to read",
    starterProgress: (current: number, total: number) => `Chapter ${current} of ${total}`,
    freeChapter: "The story continues",
    q1: "What’s the first memory that comes to mind when you think of them?",
    q2: "What’s something you want everyone to know about them?",
    q3: "What were they known for?",
    q4: "In one word, how would you describe this person?",
    q5: "What do you think mattered most to them?",
    qFree: "Write any story you want.",
    qKnownFor: (name: string) => `What is something |||${name}||| was known for?`,
    qDescribe: (name: string) => `In one word, how would you describe |||${name}|||?`,
    qFirstMemory: (name: string) => `What’s the first memory that comes to mind when you think of |||${name}|||?`,
    qEveryoneKnow: (name: string) => `What’s something you want everyone to know about |||${name}|||?`,
    qMatteredMost: (name: string) => `What do you think mattered most to |||${name}|||?`,
    starterComplete: "Starter questions complete. The rest of the book is yours to write.",
  },
  es: {
    welcomeTitle: "VitaMyStory",
    welcomeBody: "Un lugar sencillo para guardar las historias que importan.",
    savedDevice: "Las historias viven en este dispositivo.",
    demoNoteTitle: "Cómo funciona esta Demo",
    demoNoteBody: "Tus historias se guardan en tu navegador. Puedes exportar un respaldo cuando quieras para conservarlas.",
    whoFor: "¿Sobre quién escribiremos?",
    placeholder: "Abuela Elvia",
    justName: "Solo un nombre para empezar un capítulo.",
    continue: "Continuar",
    chooseExisting: "O elige a alguien más",
    introTitle: "Un santuario para recuerdos",
    introBody: (name: string) => 
      `VitaMyStory es el lugar donde aseguramos que el legado de |||${name}||| nunca se apague.\n\nNo hay prisa. Tómate tu tiempo. Captura una historia a la vez y compártela con tu familia.`,
    startWriting: "Comenzar a escribir",
    writeTitle: "Comparte un recuerdo",
    writeSubtitle: "Tómate tu tiempo. Unas pocas frases es perfecto.",
    writePlaceholder: "Empieza a escribir aquí...",
    saveStory: "Guardar recuerdo",
    updateStory: "Actualizar recuerdo",
    viewStories: "Leer historias",
    viewAllStories: (name: string) => `Leer todo sobre ${name}`,
    addAnother: "Escribir otra",
    invite: "Invitar familia", 
    inviteMsg: (name: string) => `Estoy guardando las historias de ${name} en VitaMyStory. Únete a mí.`,
    milestoneMsg: (name: string) => `¡Mira lo que hice con la historia de ${name}! Acabo de desbloquear la insignia de Guardián de Historias en VitaMyStory.`, 
    shareMilestone: "Comparte este logro con tu familia",
    storyKeeperTooltip: "Eres un Guardián de Historias.",
    badgeModalTitle: "Eres un Guardián de Historias.",
    badgeModalBody: "Has preservado 5 historias. Sigue compartiendo para desbloquear nuevas funciones.",
    close: "Cerrar",
    storySaved: "Recuerdo guardado.",
    storyShared: "Historia compartida",
    firstStorySaved: "Primer recuerdo guardado.",
    firstStorySavedPerson: (name: string) => `Tu primera historia sobre ${name} está segura.`, 
    storySavedTitle: "Recuerdo guardado.",
    storySavedBody: "Este momento está seguro.",
    firstStoryTitle: "El primer capítulo comienza.",
    firstStoryBody: "Has iniciado un legado.",
    secondStoryTitle: "Dos historias guardadas.",
    secondStoryBody: "Vas muy bien. Completa 5 historias para desbloquear funciones especiales.",
    storyKeeperTitle: "Guardián de Historias",
    storyKeeperBody: (name: string) =>
      `Has completado el primer capítulo del legado de ${name}.`,
    storyKeeperBadge: "Guardián",
    storiesOf: "LAS HISTORIAS DE",
    storyOf: "LA HISTORIA DE",
    change: "Cambiar",
    emptyHome: "Una página en blanco esperando recuerdos. Empieza cuando quieras.",
    writeAStory: "Escribir historia",
    newPerson: "Nueva persona",
    resetApp: "Reiniciar app",
    choosePerson: "Elige una persona",
    noPeople: "No hay capítulos aún.",
    back: "Regresar",
    added: "Iniciado",
    demoBanner: "Versión Demo: Las historias viven en tu navegador. Expórtalas para guardarlas.",
    saveBackup: "Exportar Respaldo",
    inviteLink: "Invitar familia (Pronto)",
    backupDownloaded: "Archivo de respaldo descargado.",
    confirmDeleteTitle: "¿Borrar este recuerdo?",
    confirmDeleteBody: "Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    confirm: "Borrar",
    copied: "Copiado al portapapeles",
    swipeHint: "Desliza para leer",
    starterProgress: (current: number, total: number) => `Capítulo ${current} de ${total}`,
    freeChapter: "La historia continúa",
    q1: "¿Cuál es el primer recuerdo que te viene a la mente cuando piensas en ellos?",
    q2: "¿Qué es algo que quieres que todos sepan sobre ellos?",
    q3: "¿Por qué cosa eran conocidos?",
    q4: "En una palabra, ¿cómo describirías a esta persona?",
    q5: "¿Qué crees que era lo que más les importaba?",
    qFree: "Escribe cualquier historia que quieras.",
    qKnownFor: (name: string) => `¿Qué es algo por lo que |||${name}||| era conocido/a?`,
    qDescribe: (name: string) => `En una palabra, ¿cómo describirías a |||${name}|||?`,
    qFirstMemory: (name: string) => `¿Cuál es el primer recuerdo que te viene a la mente al pensar en |||${name}|||?`,
    qEveryoneKnow: (name: string) => `¿Qué es algo que quieres que todos sepan sobre |||${name}|||?`,
    qMatteredMost: (name: string) => `¿Qué crees que era lo que más le importaba a |||${name}|||?`,
    starterComplete: "Preguntas iniciales completas. El resto del libro es tuyo.",
  },
};

export const LS = {
  people: "vms_people_v0",
  activePersonId: "vms_active_person_id_v0",
  questionState: "vms_weekly_question_state_v0",
  draftPrefix: "vms_draft_v0_",
  usedPrefix: "vms_used_questions_v0_",
  badgesPrefix: "vms_badges_v0_",
  lang: "vms_lang_v0",
};
