import { Lang } from "../types";

export const TEXT = {
  en: {
    heroTagline: "Begin your legacy.",
    heroSubtagline: "Preserve the stories that matter most.",
    welcomeTitle: "VitaMyStory",
    welcomeBody: "A simple place to collect the stories that matter.",
    savedDevice: "Stories live on this device.",
    demoNoteTitle: "How saving works",
    demoNoteBody: "Create an account to back up your stories to the cloud. Without an account, they only live on this device and could be lost.",
    whoFor: "Who are we writing about?",
    placeholder: "Grandma Elvia",
    justName: "Just a name to start a chapter.",
    continue: "Continue",
    chooseExisting: "Or choose an existing person",
    introTitle: "A place for meaningful stories",
    introBody: (name: string) =>
      `VitaMyStory is a place to hold |||${name}|||’s stories, moments, and memories.\n\nThere is no rush here. Take your time. Capture one story at a time and share them with your family.`,
    startWriting: "Start Writing",
    writeTitle: "Share a memory",
    writeSubtitle: "Don't overthink it. A few sentences is perfect.",
    writePlaceholder: "Start writing here...",
    saveStory: "Save this memory",
    updateStory: "Update memory",
    viewStories: "Read stories",
    viewAllStories: (name: string) => `Read all stories about ${name}`,
    addAnother: "Write another",
    invite: "Invite family",
    inviteMsg: (name: string) => `I am capturing ${name}'s stories on VitaMyStory. Join me.`,
    milestoneMsg: (name: string) => `Look what I did with ${name}'s story! I just unlocked the Story Keeper badge on VitaMyStory.`,
    shareMilestone: "Share this milestone with your family",
    storyKeeperTooltip: "You are a Story Keeper.",
    badgeModalTitle: "You are a Story Keeper.",
    badgeModalBody: "You’ve preserved 5 stories. Each one adds depth to the story you’re building.",
    close: "Close",
    storySaved: "Memory kept.",
    storyShared: "Story shared",
    firstStorySaved: "First memory saved.",
    firstStorySavedPerson: (name: string) => `Your first story about ${name} is safe.`,
    storySavedTitle: "Memory kept.",
    storySavedBody: "This moment is safe.",
    firstStoryTitle: "The first chapter begins.",
    firstStoryBody: "You have started a legacy.",
    secondStoryTitle: "Two stories saved.",
    secondStoryBody: "You are building momentum. Complete 5 stories to unlock special features.",
    storyKeeperTitle: "Story Keeper",
    storyKeeperBody: (name: string) =>
      `You’ve preserved the first chapter of |||${name}|||’s story.`,
    storyKeeperBadge: "Story Keeper",
    storiesOf: "THE STORIES OF",
    storyOf: "THE STORY OF",
    change: "Change",
    emptyHomeTitle: "Start when you’re ready",
    emptyHome: "Nothing here yet — and that’s okay. Start with one memory whenever you’re ready.",
    writeAStory: "Write a story",
    newPerson: "New person",
    resetApp: "Reset app",
    choosePerson: "Select a person",
    noPeople: "No chapters yet.",
    back: "Go back",
    added: "Started",
    demoBanner: "Demo Version: Stories live in your browser cache. Export them to keep them safe.",
    saveBackup: "Export Backup",
    inviteLink: "Invite family (Coming Soon)",
    backupDownloaded: "Backup file downloaded.",
    confirmDeleteTitle: "Delete this memory?",
    confirmDeleteBody: "This action cannot be undone.",
    cancel: "Cancel",
    confirm: "Delete",
    copied: "Copied to clipboard",
    swipeHint: "Swipe to read",
    starterProgress: (current: number, total: number) => `Chapter ${current} of ${total}`,
    freeChapter: "The story continues",
    q1: "What’s the first memory that comes to mind when you think of them?",
    q2: "What’s something you want everyone to know about them?",
    q3: "What are they best known for?",
    q4: "In one word, how would you describe this person?",
    q5: "What mattered most to this person?",
    qFree: "Share a story or picture, anything you want.",
    qKnownFor: (name: string) => `How do you think |||${name}||| will be remembered?`,
    qDescribe: (name: string) => `In one word, how would you describe |||${name}|||?`,
    qFirstMemory: (name: string) => `What’s the first memory that comes to mind when you think of |||${name}|||?`,
    qEveryoneKnow: (name: string) => `What’s something you want everyone to know about |||${name}|||?`,
    qMatteredMost: (name: string) => `What mattered most to |||${name}|||?`,
    qPhoto: (name: string) => `Here is a photo that reminds me of |||${name}|||...`,
    qAudio: (name: string) => `This audio reminds me of |||${name}|||...`,
    starterComplete: "Starter questions complete. The rest of the book is yours to write.",
    // Auth
    login: "Log in",
    register: "Create account",
    loginSubtitle: "Welcome back. Your stories are waiting.",
    registerSubtitle: "Create an account to save your stories.",
    email: "Email",
    password: "Password",
    passwordHint: "At least 6 characters",
    loginBtn: "Log in",
    registerBtn: "Create account",
    loading: "Loading...",
    noAccount: "Don't have an account? Create one",
    hasAccount: "Already have an account? Log in",
    forgotPassword: "Forgot password?",
    resetSubtitle: "Enter your email to receive a password reset link.",
    resetBtn: "Send reset link",
    resetLinkSent: "Email sent! Check your inbox and spam folder.",
    logout: "Log out",
    loggedInAs: "Logged in as",
    listening: "Listening...",
    tapToSpeak: "Tap to speak",
    shareStory: "Share this story",
    shareSuccess: "Story copied to clipboard",
    whenHappened: "When did this happen? (Optional)",
    datePlaceholder: "e.g. 1985, Summer '92, When I was 10...",
    inspireMe: "Inspire me",
    imagePrompt: "What does this remind you of?",
    saving: "Saving...",
    profileTitle: "Profile",
    identity: "Identity",
    experience: "Experience",
    collection: "Collection",
    exportCollection: "Export Collection",
    clearData: "Clear Data",
    signOut: "Sign Out",
    secureStoriesTitle: "Secure your stories",
    secureStoriesBody: "Create an account to backup your collection and access it from any device.",
    guestMode: "GUEST MODE",
    guestNote: "Guest mode is for trial only. Log in is recommended to save your stories forever.",
    tapToName: "Tap to name...",
    displayNameHint: "This name will appear when you share stories with family.",
    resetConfirm: "Reset all data? This cannot be undone.",
    navHome: "Home",
    navStories: "Stories",
    navFamily: "Family",
    navProfile: "Profile",
    navInbox: "Inbox",
    navNotifications: "Updates",
    notificationsTitle: "Notifications",
    or: "OR",
    continueWithGoogle: "Continue with Google",
    markAllRead: "Mark all read",
    noNotifications: "No notifications.",
    familyTitle: "Your Family",
    peopleOf: "People of",
    storiesTitle: "Your Stories",
    noStories: "No stories yet.",
    writeFirstStory: "Write First Story",
    shareProfile: "Share Profile",
    editName: "Edit Name",
    deleteProfile: "Delete Profile",
    deleteProfileConfirmTitle: "Delete this person?",
    deleteProfileConfirmBody: (name: string) => `This will permanently delete ${name} and all their stories. This cannot be undone.`,
    renameTitle: "Edit Name",
    renamePlaceholder: "New Name",
    renameSave: "Save Name",
    chapter: "Chapter",
    newStoryTitle: "New Story",
    customStoryPlaceholder: "Story title",
    newStorySubtitle: "Start the next chapter",
    newPhotoTitle: "New Photo",
    newPhotoSubtitle: "Capture a moment",
    newAudioTitle: "New Audio",
    newAudioSubtitle: "Record a voice memory",
    of: "of",
    inspiredBy: "Inspired by you",
    inspirationPrefix: "Something like...",
    notificationSaw: "Someone saw your story",
    notificationSawBody: "Someone just viewed the memory you shared.",
    notificationLike: "Someone liked your story",
    notificationLikeBody: "Someone loved your story!",
    notificationNew: "Someone just shared a story",
    notificationWelcomeTitle: "Welcome home.",
    notificationWelcomeBody: "Your account is ready. Your stories are safe.",
    notificationPersonCreatedTitle: "A new chapter begins.",
    notificationPersonCreatedBody: "You've started a new story. Keep writing to build their legacy.",
    notificationMilestoneTitle: "Milestone Unlocked!",
    support: "Help & Feedback",
    contactTitle: "Contact Us",
    contactSubtitle: "Have a suggestion or need help? We'd love to hear from you.",
    contactBtn: "Send us an email",
    shareMainMsg: (name: string) => `📖 I'm preserving a story about ${name} on VitaMyStory. (the app)`,
    shareVisitMsg: "✨ Shared via VitaMyStory — Where stories live forever.",
    shareCollectionMsg: "🔗 Click here to start your own legacy:",
    theme: "Appearance",
    themeLight: "Light Mode",
    themeDark: "Midnight Library",
    refineStory: "Refine Story",
    refining: "Refining...",
    refineTitle: "Journalist Edition",
    original: "Your Original",
    refined: "Refined Version",
    useRefinement: "Use Refinement",
    keepOriginal: "Keep Original",
    refineAgain: "Try another version",
    limitReached: "Free version limit reached. Stick with one of these or upgrade.",
    nudgeTryAnother: "Next?",
    nudgeSwipe: "Swipe for more",
    errorTitle: "Something went wrong",
    downloadSuccessTitle: "Memory Saved",
    downloadSuccessBody: "This story has been saved to your device.",
    success: "Success",
    error: "Error",
    privateShareTitle: "This story is private",
    privateShareBody: "Only you can see this story. Make it public first to share it.",
    photoUpdated: "Photo updated successfully",
    lockedTitle: "Unlock New Modes",
    lockedSubtitle: "Complete 5 chapters to unlock Smart Questions.",
    lockedHeroTitle: "Your story is just beginning.",
    lockedHeroTitleKeepGoing: "Every memory you save matters.",
    chaptersCompleted: "Chapters Completed",
    continueJourney: "Continue Journey",
    changeQuestion: "Change Question",
    unlockedModesTitle: "New Modes Unlocked!",
    unlockedModesBody: "You've unlocked Photo, Audio, and Custom Story modes. Continue your legacy!",
    aiQuestionsTitle: "Smart Questions",
    aiQuestionsSubtitle: "AI learns from your stories to craft questions only you can answer",
    aiQuestionsLocked: "Complete these milestones to unlock:",
    milestone5Stories: "5 Stories",
    milestonePhotoStory: "Photo Story",
    milestoneAudioStory: "Audio Story",
    milestoneProfilePhoto: "Profile Photo",
    aiQuestionsUnlockedTitle: "Smart Questions Unlocked!",
    aiQuestionsUnlockedBody: "The more you write, the smarter they get. These questions are crafted by AI, learned from your own stories — written just for you.",
    generateMoreQuestions: "Generate More Questions",
    generatingQuestions: "Generating...",
    aiQuestionsDescription: "AI learns from your stories to create questions only you can answer.",
    theQuestion: "The Question",
    newPhoto: "New Photo",
    newAudio: "New Audio",
    aiQuestions: "Smart Questions",
  },
  es: {
    heroTagline: "Comienza tu legado.",
    heroSubtagline: "Preserva las historias que más importan.",
    welcomeTitle: "VitaMyStory",
    welcomeBody: "Un lugar sencillo para guardar las historias que importan.",
    savedDevice: "Las historias viven en este dispositivo.",
    demoNoteTitle: "Cómo funciona el guardado",
    demoNoteBody: "Crea una cuenta para respaldar tus historias en la nube. Sin una cuenta, solo viven en este dispositivo y podrían perderse.",
    whoFor: "¿Sobre quién escribiremos?",
    placeholder: "Abuela Elvia",
    justName: "Solo un nombre para empezar un capítulo.",
    justNameHint: "Solo un nombre para empezar un capítulo.",
    continue: "Continuar",
    chooseExisting: "O elige a alguien más",
    introTitle: "Un santuario para recuerdos",
    introBody: (name: string) =>
      `VitaMyStory es el lugar donde aseguramos que el legado de |||${name}||| nunca se apague.\n\nNo hay prisa. Tómate tu tiempo. Captura una historia a la vez y compártela con tu familia.`,
    startWriting: "Comenzar a escribir",
    writeTitle: "Comparte un recuerdo",
    writeSubtitle: "Tómate tu tiempo. Unas pocas frases es perfecto.",
    writePlaceholder: "Empieza a escribir aquí...",
    saveStory: "Guardar recuerdo",
    updateStory: "Actualizar recuerdo",
    viewStories: "Leer historias",
    viewAllStories: (name: string) => `Leer todo sobre ${name}`,
    addAnother: "Escribir otra",
    invite: "Invitar familia",
    inviteMsg: (name: string) => `Estoy guardando las historias de ${name} en VitaMyStory. Únete a mí.`,
    milestoneMsg: (name: string) => `¡Mira lo que hice con la historia de ${name}! Acabo de desbloquear la insignia de Guardián de Historias en VitaMyStory.`,
    shareMilestone: "Comparte este logro con tu familia",
    storyKeeperTooltip: "Eres un Guardián de Historias.",
    badgeModalTitle: "Eres un Guardián de Historias.",
    badgeModalBody: "Has preservado 5 historias. Sigue compartiendo para desbloquear nuevas funciones.",
    close: "Cerrar",
    storySaved: "Recuerdo guardado.",
    storyShared: "Historia compartida",
    firstStorySaved: "Primer recuerdo guardado.",
    firstStorySavedPerson: (name: string) => `Tu primera historia sobre ${name} está segura.`,
    storySavedTitle: "Recuerdo guardado.",
    storySavedBody: "Este momento está seguro.",
    firstStoryTitle: "El primer capítulo comienza.",
    firstStoryBody: "Has iniciado un legado.",
    secondStoryTitle: "Dos historias guardadas.",
    secondStoryBody: "Vas muy bien. Completa 5 historias para desbloquear funciones especiales.",
    storyKeeperTitle: "Guardián de Historias",
    storyKeeperBody: (name: string) =>
      `Has completado el primer capítulo del legado de |||${name}|||.`,
    storyKeeperBadge: "Guardián",
    storiesOf: "LAS HISTORIAS DE",
    storyOf: "LA HISTORIA DE",
    change: "Cambiar",
    emptyHomeTitle: "Inicia tu legado",
    emptyHome: "Una página en blanco esperando recuerdos. Empieza cuando quieras.",
    writeAStory: "Escribir historia",
    newPerson: "Nueva persona",
    resetApp: "Reiniciar app",
    choosePerson: "Elige una persona",
    noPeople: "No hay capítulos aún.",
    back: "Regresar",
    added: "Iniciado",
    demoBanner: "Versión Demo: Las historias viven en tu navegador. Expórtalas para guardarlas.",
    saveBackup: "Exportar Respaldo",
    inviteLink: "Invitar familia (Pronto)",
    backupDownloaded: "Archivo de respaldo descargado.",
    confirmDeleteTitle: "¿Borrar este recuerdo?",
    confirmDeleteBody: "Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    confirm: "Borrar",
    copied: "Copiado al portapapeles",
    swipeHint: "Desliza para leer",
    starterProgress: (current: number, total: number) => `Capítulo ${current} de ${total}`,
    freeChapter: "La historia continúa",
    q1: "¿Cuál es el primer recuerdo que te viene a la mente cuando piensas en ellos?",
    q2: "¿Qué es algo que quieres que todos sepan sobre ellos?",
    q3: "¿Cómo crees que será mejor recordado/a?",
    q4: "In una palabra, ¿cómo describirías a esta persona?",
    q5: "¿Qué era lo que más le importaba a esta persona?",
    qFree: "Comparte una historia o foto, lo que desees.",
    qKnownFor: (name: string) => `¿Cómo crees que será mejor recordado/a |||${name}|||?`,
    qDescribe: (name: string) => `En una palabra, ¿cómo describirías a |||${name}|||?`,
    qFirstMemory: (name: string) => `¿Cuál es el primer recuerdo que te viene a la mente al pensar en |||${name}|||?`,
    qEveryoneKnow: (name: string) => `¿Qué es algo que quieres que todos sepan sobre |||${name}|||?`,
    qMatteredMost: (name: string) => `¿Qué era lo que más le importaba a |||${name}|||?`,
    qPhoto: (name: string) => `Esta foto me recuerda a |||${name}|||...`,
    qAudio: (name: string) => `Este audio me recuerda a |||${name}|||...`,
    starterComplete: "Preguntas iniciales completas. El resto del libro es tuyo.",
    // Auth
    login: "Iniciar sesión",
    register: "Crear cuenta",
    loginSubtitle: "Bienvenido de vuelta. Tus historias te esperan.",
    registerSubtitle: "Crea una cuenta para guardar tus historias.",
    email: "Correo electrónico",
    password: "Contraseña",
    passwordHint: "Al menos 6 caracteres",
    loginBtn: "Iniciar sesión",
    registerBtn: "Crear cuenta",
    loading: "Cargando...",
    noAccount: "¿No tienes cuenta? Crea una",
    hasAccount: "¿Ya tienes cuenta? Inicia sesión",
    forgotPassword: "¿Olvidaste tu contraseña?",
    resetSubtitle: "Ingresa tu correo para recibir un enlace de recuperación.",
    resetBtn: "Enviar enlace",
    resetLinkSent: "¡Correo enviado! Revisa tu bandeja y carpeta de spam.",
    logout: "Cerrar sesión",
    loggedInAs: "Sesión iniciada como",
    listening: "Escuchando...",
    tapToSpeak: "Toca para hablar",
    shareStory: "Compartir historia",
    shareSuccess: "Historia copiada al portapapeles",
    whenHappened: "¿Cuándo pasó esto? (Opcional)",
    datePlaceholder: "ej. 1985, Verano del '92, Cuando tenía 10...",
    inspireMe: "Inspirame",
    imagePrompt: "¿Qué te recuerda esto?",
    saving: "Guardando...",
    profileTitle: "Perfil",
    identity: "Identidad",
    experience: "Experiencia",
    collection: "Colección",
    exportCollection: "Exportar Colección",
    clearData: "Borrar Datos",
    signOut: "Cerrar Sesión",
    secureStoriesTitle: "Protege tus historias",
    secureStoriesBody: "Crea una cuenta para respaldar tu colección y acceder desde cualquier dispositivo.",
    guestMode: "MODO INVITADO",
    guestNote: "El modo invitado es solo de prueba. Se recomienda iniciar sesión para guardar tus historias para siempre.",
    tapToName: "Toca para nombrar...",
    displayNameHint: "Este nombre aparecerá cuando compartas historias con tu familia.",
    resetConfirm: "¿Borrar todos los datos? Esta acción no se puede deshacer.",
    navHome: "Inicio",
    navStories: "Historias",
    navFamily: "Familia",
    navProfile: "Perfil",
    navInbox: "Bandeja",
    navNotifications: "Avisos",
    notificationsTitle: "Notificaciones",
    or: "O",
    continueWithGoogle: "Continuar con Google",
    markAllRead: "Marcar leídas",
    noNotifications: "No hay notificaciones.",
    familyTitle: "Tu Familia",
    peopleOf: "Familia de",
    storiesTitle: "Tus Historias",
    noStories: "No hay historias aún.",
    writeFirstStory: "Escribir primera historia",
    shareProfile: "Compartir Perfil",
    editName: "Editar Nombre",
    deleteProfile: "Borrar Perfil",
    deleteProfileConfirmTitle: "¿Borrar a esta persona?",
    deleteProfileConfirmBody: (name: string) => `Esto borrará permanentemente a ${name} y todas sus historias. No se puede deshacer.`,
    renameTitle: "Editar Nombre",
    renamePlaceholder: "Nuevo Nombre",
    renameSave: "Guardar",
    chapter: "Capítulo",
    newStoryTitle: "Nueva Historia",
    customStoryPlaceholder: "Título de la historia",
    newStorySubtitle: "Empieza el próximo capítulo",
    newPhotoTitle: "Nueva Foto",
    newPhotoSubtitle: "Guarda un momento",
    newAudioTitle: "Nuevo Audio",
    newAudioSubtitle: "Graba una memoria de voz",
    of: "de",
    inspiredBy: "Inspirado por ti",
    inspirationPrefix: "Algo como...",
    notificationSaw: "Alguien vio tu historia",
    notificationSawBody: "Alguien acaba de ver el recuerdo que compartiste.",
    notificationLike: "A alguien le gustó tu historia",
    notificationLikeBody: "¡A alguien le encantó tu historia!",
    notificationNew: "Alguien acaba de compartir una historia",
    notificationWelcomeTitle: "Bienvenido a casa.",
    notificationWelcomeBody: "Tu cuenta está lista. Tus historias están seguras.",
    notificationPersonCreatedTitle: "Comienza un nuevo capítulo.",
    notificationPersonCreatedBody: "Has iniciado una nueva historia. Sigue escribiendo para construir su legado.",
    notificationMilestoneTitle: "¡Hito Desbloqueado!",
    support: "Ayuda y Comentarios",
    contactTitle: "Contáctanos",
    contactSubtitle: "¿Tienes una sugerencia o necesitas ayuda? Nos encantaría escucharte.",
    contactBtn: "Envíanos un correo",
    shareMainMsg: (name: string) => `📖 Estoy guardando una historia sobre ${name} en VitaMyStory. (the app)`,
    shareVisitMsg: "✨ Compartido vía VitaMyStory — Donde las historias viven para siempre.",
    shareCollectionMsg: "🔗 Haz clic aquí para comenzar tu legado:",
    theme: "Apariencia",
    themeLight: "Modo Claro",
    themeDark: "Biblioteca Nocturna",
    refineStory: "Pulir Historia",
    refining: "Puliendo...",
    refineTitle: "Edición Periodística",
    original: "Tu Original",
    refined: "Versión Pulida",
    useRefinement: "Usar Versión Pulida",
    keepOriginal: "Mantener Original",
    refineAgain: "Probar otra versión",
    limitReached: "Límite de versión gratuita. Elige una de estas o mejora tu plan.",
    nudgeTryAnother: "¿Siguiente?",
    nudgeSwipe: "Desliza para ver más",
    errorTitle: "Algo salió mal",
    downloadSuccessTitle: "Recuerdo Guardado",
    downloadSuccessBody: "Esta historia se ha guardado en tu dispositivo.",
    success: "Éxito",
    error: "Error",
    privateShareTitle: "Esta historia es privada",
    privateShareBody: "Solo tú puedes ver esta historia. Hazla pública primero para compartirla.",
    photoUpdated: "Foto actualizada con éxito",
    lockedTitle: "Desbloquea Nuevos Modos",
    lockedSubtitle: "Completa 5 capítulos para desbloquear Preguntas Inteligentes.",
    lockedHeroTitle: "Tu historia apenas comienza.",
    lockedHeroTitleKeepGoing: "Cada recuerdo que guardas importa.",
    chaptersCompleted: "Capítulos Completados",
    continueJourney: "Continuar Viaje",
    changeQuestion: "Cambiar Pregunta",
    unlockedModesTitle: "¡Nuevos Modos Desbloqueados!",
    unlockedModesBody: "Has desbloqueado los modos Foto, Audio e Historia Libre. ¡Continúa tu legado!",
    aiQuestionsTitle: "Preguntas Inteligentes",
    aiQuestionsSubtitle: "La IA aprende de tus historias para crear preguntas que solo tú puedes responder",
    aiQuestionsLocked: "Completa estos hitos para desbloquear:",
    milestone5Stories: "5 Historias",
    milestonePhotoStory: "Historia con Foto",
    milestoneAudioStory: "Historia con Audio",
    milestoneProfilePhoto: "Foto de Perfil",
    aiQuestionsUnlockedTitle: "¡Preguntas Inteligentes Desbloqueadas!",
    aiQuestionsUnlockedBody: "Cuanto más escribes, más inteligentes se vuelven. Estas preguntas son creadas por IA, aprendidas de tus propias historias — escritas solo para ti.",
    generateMoreQuestions: "Generar Más Preguntas",
    generatingQuestions: "Generando...",
    aiQuestionsDescription: "La IA aprende de tus historias para crear preguntas que solo tú puedes responder.",
    theQuestion: "La Pregunta",
    newPhoto: "Nueva Foto",
    newAudio: "Nuevo Audio",
    aiQuestions: "Preguntas Inteligentes",
  },
};

export const QUESTION_EXAMPLES = {
  en: {
    0: "I remember the sound of her laugh during Sunday dinners...", // q1: First memory
    1: "I want them to know she always put her family first…", // q2: What everyone should know
    2: "I remember the way she'd stay up late just to braid my hair before school...", // q3: Memory
    3: "Protective · Energetic · Devoted", // q4: One word description
    4: "Her family is everything to her...", // q5: Mattered most
  },
  es: {
    0: "Recuerdo el sonido de su risa durante las cenas del domingo...",
    1: "Quiero que sepan que siempre puso a su familia primero…",
    2: "Recuerdo cómo se quedaba despierta tarde solo para trenzarme el cabello antes de la escuela...",
    3: "Protección · Energía · Compromiso",
    4: "Su familia lo es todo para ella...",
  }
};

export const LS = {
  people: "vms_people_v0",
  activePersonId: "vms_active_person_id_v0",
  questionState: "vms_weekly_question_state_v0",
  draftPrefix: "vms_draft_v0_",
  usedPrefix: "vms_used_questions_v0_",
  badgesPrefix: "vms_badges_v0_",
  lang: "vms_lang_v0",
};

// First-person questions for "My Story" self-profile mode
export const SELF_QUESTIONS: Record<"en" | "es", string[]> = {
  en: [
    // Childhood & Roots
    "What's your earliest childhood memory?",
    "Where did you grow up, and what did it feel and smell like?",
    "What did a typical day look like when you were a child?",
    "What games or activities did you love as a kid?",
    "Who was your biggest childhood hero — real or fictional?",
    // Family & People
    "Who in your family shaped who you are the most, and how?",
    "What's a story about your parents that you often think about?",
    "What's something you wish you had told someone in your family while you had the chance?",
    "What's a tradition from your childhood that you've tried to keep alive?",
    "Who was your first best friend, and what do you remember about them?",
    // Identity & Turning Points
    "What's a decision you made that changed the course of your life?",
    "What did you believe at 20 that you no longer believe today?",
    "When did you first feel like an adult? What happened?",
    "What's something you outgrew — a version of yourself you've left behind?",
    "What's a risk you took that you're glad you did?",
    // Work & Purpose
    "What's the work or project in your life you're most proud of?",
    "What were you doing when you felt most alive?",
    "What job or responsibility surprised you the most — felt nothing like you expected?",
    "What did you want to be when you grew up? How close did you get?",
    "What does a good day look like to you?",
    // Love & Relationships
    "How did you meet the people who matter most to you in your life?",
    "What's your definition of a good friendship, and who in your life fits it?",
    "What's the kindest thing someone has ever done for you without being asked?",
    "What's a love story in your life — romantic or otherwise?",
    "What's something you do for others that almost no one knows about?",
    // Wisdom & Reflection
    "What do you know now that you wish you had known at 30?",
    "What's a piece of advice you've carried with you for years?",
    "What's a mistake you made that turned into something valuable?",
    "What's the best thing about the decade of life you're in right now?",
    "What question do you most wish someone would ask you?",
    // Legacy & Looking Forward
    "What do you want the next generation to remember about you?",
    "What's something about your life you hope your family never forgets?",
    "What's a story from your life that only you can tell?",
    "If you could write a letter to yourself 20 years ago, what's the first thing you'd say?",
    "What does a life well-lived mean to you?",
  ],
  es: [
    // Infancia y Raíces
    "¿Cuál es tu primer recuerdo de la infancia?",
    "¿Dónde creciste y cómo era ese lugar — qué se sentía, qué olores había?",
    "¿Cómo era un día típico cuando eras niño o niña?",
    "¿Qué juegos o actividades te encantaban de pequeño/a?",
    "¿Quién fue tu mayor héroe o heroína de la infancia — real o ficticio/a?",
    // Familia y Personas
    "¿Quién en tu familia formó más tu manera de ser y por qué?",
    "¿Cuál es una historia de tus padres en la que piensas seguido?",
    "¿Qué le hubieras dicho a alguien de tu familia que ya no puedes decirle?",
    "¿Qué tradición de tu infancia has intentado mantener viva?",
    "¿Quién fue tu primer mejor amigo o amiga y qué recuerdas de esa amistad?",
    // Identidad y Momentos Clave
    "¿Qué decisión tomaste que cambió el rumbo de tu vida?",
    "¿Qué creías a los 20 años que ya no crees hoy?",
    "¿Cuándo sentiste por primera vez que eras adulto/a? ¿Qué pasó?",
    "¿Qué versión de ti mismo/a has dejado atrás — algo que superaste?",
    "¿Qué riesgo tomaste del que te alegras haber tomado?",
    // Trabajo y Propósito
    "¿Cuál es el trabajo o proyecto del que te sientes más orgulloso/a?",
    "¿Qué estabas haciendo cuando te sentiste más vivo/a?",
    "¿Qué trabajo o responsabilidad te sorprendió más — fue muy distinto a lo que esperabas?",
    "¿Qué querías ser de grande? ¿Qué tan cerca llegaste?",
    "¿Cómo es para ti un buen día?",
    // Amor y Relaciones
    "¿Cómo conociste a las personas más importantes de tu vida?",
    "¿Qué es para ti una buena amistad, y quién en tu vida la representa?",
    "¿Cuál es la cosa más amable que alguien hizo por ti sin que se lo pidieras?",
    "¿Cuál es una historia de amor en tu vida — romántica o de otro tipo?",
    "¿Qué haces por los demás que casi nadie sabe?",
    // Sabiduría y Reflexión
    "¿Qué sabes hoy que ojalá hubieras sabido a los 30?",
    "¿Cuál es un consejo que llevas contigo desde hace muchos años?",
    "¿Qué error cometiste que se convirtió en algo valioso?",
    "¿Qué es lo mejor de la etapa de vida en la que estás ahora?",
    "¿Qué pregunta desearías que alguien te hiciera?",
    // Legado y Futuro
    "¿Qué quieres que la próxima generación recuerde de ti?",
    "¿Qué de tu vida esperas que tu familia nunca olvide?",
    "¿Cuál es una historia de tu vida que solo tú puedes contar?",
    "Si pudieras escribirle una carta a tu yo de hace 20 años, ¿qué le dirías primero?",
    "¿Qué significa para ti haber vivido bien?",
  ],
};

