import { Lang } from "../types";

export const TEXT = {
  en: {
    welcomeTitle: "VitaMyStory",
    welcomeBody: "A simple place to collect the stories that matter.",
    savedDevice: "Stories live on this device.",
    demoNoteTitle: "How saving works",
    demoNoteBody: "Create an account to back up your stories to the cloud. Without an account, they only live on this device and could be lost.",
    whoFor: "Who are we writing about?",
    placeholder: "Grandma Elvia",
    justName: "Just a name to start a chapter.",
    continue: "Continue",
    chooseExisting: "Or choose an existing person",
    introTitle: "A place for meaningful stories",
    introBody: (name: string) =>
      `VitaMyStory is a place to hold |||${name}|||’s stories, moments, and memories.\n\nThere is no rush here. Take your time. Capture one story at a time and share them with your family.`,
    startWriting: "Start Writing",
    writeTitle: "Share a memory",
    writeSubtitle: "Don't overthink it. A few sentences is perfect.",
    writePlaceholder: "Start writing here...",
    saveStory: "Save this memory",
    updateStory: "Update memory",
    viewStories: "Read stories",
    viewAllStories: (name: string) => `Read all stories about ${name}`,
    addAnother: "Write another",
    invite: "Invite family",
    inviteMsg: (name: string) => `I am capturing ${name}'s stories on VitaMyStory. Join me.`,
    milestoneMsg: (name: string) => `Look what I did with ${name}'s story! I just unlocked the Story Keeper badge on VitaMyStory.`,
    shareMilestone: "Share this milestone with your family",
    storyKeeperTooltip: "You are a Story Keeper.",
    badgeModalTitle: "You are a Story Keeper.",
    badgeModalBody: "You’ve preserved 5 stories. Each one adds depth to the story you’re building.",
    close: "Close",
    storySaved: "Memory kept.",
    storyShared: "Story shared",
    firstStorySaved: "First memory saved.",
    firstStorySavedPerson: (name: string) => `Your first story about ${name} is safe.`,
    storySavedTitle: "Memory kept.",
    storySavedBody: "This moment is safe.",
    firstStoryTitle: "The first chapter begins.",
    firstStoryBody: "You have started a legacy.",
    secondStoryTitle: "Two stories saved.",
    secondStoryBody: "You are building momentum. Complete 5 stories to unlock special features.",
    storyKeeperTitle: "Story Keeper",
    storyKeeperBody: (name: string) =>
      `You’ve preserved the first chapter of ${name}’s story.`,
    storyKeeperBadge: "Story Keeper",
    storiesOf: "THE STORIES OF",
    storyOf: "THE STORY OF",
    change: "Change",
    emptyHomeTitle: "Start when you’re ready",
    emptyHome: "Nothing here yet — and that’s okay. Start with one memory whenever you’re ready.",
    writeAStory: "Write a story",
    newPerson: "New person",
    resetApp: "Reset app",
    choosePerson: "Select a person",
    noPeople: "No chapters yet.",
    back: "Go back",
    added: "Started",
    demoBanner: "Demo Version: Stories live in your browser cache. Export them to keep them safe.",
    saveBackup: "Export Backup",
    inviteLink: "Invite family (Coming Soon)",
    backupDownloaded: "Backup file downloaded.",
    confirmDeleteTitle: "Delete this memory?",
    confirmDeleteBody: "This action cannot be undone.",
    cancel: "Cancel",
    confirm: "Delete",
    copied: "Copied to clipboard",
    swipeHint: "Swipe to read",
    starterProgress: (current: number, total: number) => `Chapter ${current} of ${total}`,
    freeChapter: "The story continues",
    q1: "What’s the first memory that comes to mind when you think of them?",
    q2: "What’s something you want everyone to know about them?",
    q3: "What are they best known for?",
    q4: "In one word, how would you describe this person?",
    q5: "What matters most to them?",
    qFree: "Share a story or picture, anything you want.",
    qKnownFor: (name: string) => `What is something |||${name}||| is known for?`,
    qDescribe: (name: string) => `In one word, how would you describe |||${name}|||?`,
    qFirstMemory: (name: string) => `What’s the first memory that comes to mind when you think of |||${name}|||?`,
    qEveryoneKnow: (name: string) => `What’s something you want everyone to know about |||${name}|||?`,
    qMatteredMost: (name: string) => `What matters most to |||${name}|||?`,
    starterComplete: "Starter questions complete. The rest of the book is yours to write.",
    // Auth
    login: "Log in",
    register: "Create account",
    loginSubtitle: "Welcome back. Your stories are waiting.",
    registerSubtitle: "Create an account to save your stories.",
    email: "Email",
    password: "Password",
    passwordHint: "At least 6 characters",
    loginBtn: "Log in",
    registerBtn: "Create account",
    loading: "Loading...",
    noAccount: "Don't have an account? Create one",
    hasAccount: "Already have an account? Log in",
    forgotPassword: "Forgot password?",
    resetSubtitle: "Enter your email to receive a password reset link.",
    resetBtn: "Send reset link",
    resetLinkSent: "Email sent! Check your inbox and spam folder.",
    logout: "Log out",
    loggedInAs: "Logged in as",
    listening: "Listening...",
    tapToSpeak: "Tap to speak",
    shareStory: "Share this story",
    shareSuccess: "Story copied to clipboard",
    whenHappened: "When did this happen? (Optional)",
    datePlaceholder: "e.g. 1985, Summer '92, When I was 10...",
    inspireMe: "Inspire me",
    imagePrompt: "What does this remind you of?",
    saving: "Saving...",
    profileTitle: "Profile",
    identity: "Identity",
    experience: "Experience",
    collection: "Collection",
    exportCollection: "Export Collection",
    clearData: "Clear Data",
    signOut: "Sign Out",
    secureStoriesTitle: "Secure your stories",
    secureStoriesBody: "Create an account to backup your collection and access it from any device.",
    guestMode: "GUEST MODE",
    tapToName: "Tap to name...",
    displayNameHint: "This name will appear when you share stories with family.",
    resetConfirm: "Reset all data? This cannot be undone.",
    navHome: "Home",
    navStories: "Stories",
    navFamily: "Family",
    navProfile: "Profile",
    navNotifications: "Updates",
    notificationsTitle: "Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No notifications yet.",
    familyTitle: "Your Family",
    peopleOf: "People of",
    storiesTitle: "Your Stories",
    noStories: "No stories yet.",
    writeFirstStory: "Write First Story",
    chapter: "Chapter",
    of: "of",
    inspiredBy: "Inspired by you",
    inspirationPrefix: "Something like...",
    notificationSaw: "Someone saw your story",
    notificationLike: "Someone liked your story",
    notificationNew: "Someone just shared a story",
    support: "Help & Feedback",
    contactTitle: "Contact Us",
    contactSubtitle: "Have a suggestion or need help? We'd love to hear from you.",
    contactBtn: "Send us an email",
  },
  es: {
    welcomeTitle: "VitaMyStory",
    welcomeBody: "Un lugar sencillo para guardar las historias que importan.",
    savedDevice: "Las historias viven en este dispositivo.",
    demoNoteTitle: "Cómo funciona el guardado",
    demoNoteBody: "Crea una cuenta para respaldar tus historias en la nube. Sin una cuenta, solo viven en este dispositivo y podrían perderse.",
    whoFor: "¿Sobre quién escribiremos?",
    placeholder: "Abuela Elvia",
    justName: "Solo un nombre para empezar un capítulo.",
    justNameHint: "Solo un nombre para empezar un capítulo.",
    continue: "Continuar",
    chooseExisting: "O elige a alguien más",
    introTitle: "Un santuario para recuerdos",
    introBody: (name: string) =>
      `VitaMyStory es el lugar donde aseguramos que el legado de |||${name}||| nunca se apague.\n\nNo hay prisa. Tómate tu tiempo. Captura una historia a la vez y compártela con tu familia.`,
    startWriting: "Comenzar a escribir",
    writeTitle: "Comparte un recuerdo",
    writeSubtitle: "Tómate tu tiempo. Unas pocas frases es perfecto.",
    writePlaceholder: "Empieza a escribir aquí...",
    saveStory: "Guardar recuerdo",
    updateStory: "Actualizar recuerdo",
    viewStories: "Leer historias",
    viewAllStories: (name: string) => `Leer todo sobre ${name}`,
    addAnother: "Escribir otra",
    invite: "Invitar familia",
    inviteMsg: (name: string) => `Estoy guardando las historias de ${name} en VitaMyStory. Únete a mí.`,
    milestoneMsg: (name: string) => `¡Mira lo que hice con la historia de ${name}! Acabo de desbloquear la insignia de Guardián de Historias en VitaMyStory.`,
    shareMilestone: "Comparte este logro con tu familia",
    storyKeeperTooltip: "Eres un Guardián de Historias.",
    badgeModalTitle: "Eres un Guardián de Historias.",
    badgeModalBody: "Has preservado 5 historias. Sigue compartiendo para desbloquear nuevas funciones.",
    close: "Cerrar",
    storySaved: "Recuerdo guardado.",
    storyShared: "Historia compartida",
    firstStorySaved: "Primer recuerdo guardado.",
    firstStorySavedPerson: (name: string) => `Tu primera historia sobre ${name} está segura.`,
    storySavedTitle: "Recuerdo guardado.",
    storySavedBody: "Este momento está seguro.",
    firstStoryTitle: "El primer capítulo comienza.",
    firstStoryBody: "Has iniciado un legado.",
    secondStoryTitle: "Dos historias guardadas.",
    secondStoryBody: "Vas muy bien. Completa 5 historias para desbloquear funciones especiales.",
    storyKeeperTitle: "Guardián de Historias",
    storyKeeperBody: (name: string) =>
      `Has completado el primer capítulo del legado de ${name}.`,
    storyKeeperBadge: "Guardián",
    storiesOf: "LAS HISTORIAS DE",
    storyOf: "LA HISTORIA DE",
    change: "Cambiar",
    emptyHomeTitle: "Inicia tu legado",
    emptyHome: "Una página en blanco esperando recuerdos. Empieza cuando quieras.",
    writeAStory: "Escribir historia",
    newPerson: "Nueva persona",
    resetApp: "Reiniciar app",
    choosePerson: "Elige una persona",
    noPeople: "No hay capítulos aún.",
    back: "Regresar",
    added: "Iniciado",
    demoBanner: "Versión Demo: Las historias viven en tu navegador. Expórtalas para guardarlas.",
    saveBackup: "Exportar Respaldo",
    inviteLink: "Invitar familia (Pronto)",
    backupDownloaded: "Archivo de respaldo descargado.",
    confirmDeleteTitle: "¿Borrar este recuerdo?",
    confirmDeleteBody: "Esta acción no se puede deshacer.",
    cancel: "Cancelar",
    confirm: "Borrar",
    copied: "Copiado al portapapeles",
    swipeHint: "Desliza para leer",
    starterProgress: (current: number, total: number) => `Capítulo ${current} de ${total}`,
    freeChapter: "La historia continúa",
    q1: "¿Cuál es el primer recuerdo que te viene a la mente cuando piensas en ellos?",
    q2: "¿Qué es algo que quieres que todos sepan sobre ellos?",
    q3: "¿Por qué es mejor conocido/a?",
    q4: "In una palabra, ¿cómo describirías a esta persona?",
    q5: "¿Qué es lo que más le importa?",
    qFree: "Comparte una historia o foto, lo que desees.",
    qKnownFor: (name: string) => `¿Qué es algo por lo que es conocido/a |||${name}|||?`,
    qDescribe: (name: string) => `En una palabra, ¿cómo describirías a |||${name}|||?`,
    qFirstMemory: (name: string) => `¿Cuál es el primer recuerdo que te viene a la mente al pensar en |||${name}|||?`,
    qEveryoneKnow: (name: string) => `¿Qué es algo que quieres que todos sepan sobre |||${name}|||?`,
    qMatteredMost: (name: string) => `¿Qué es lo que más le importa a |||${name}|||?`,
    starterComplete: "Preguntas iniciales completas. El resto del libro es tuyo.",
    // Auth
    login: "Iniciar sesión",
    register: "Crear cuenta",
    loginSubtitle: "Bienvenido de vuelta. Tus historias te esperan.",
    registerSubtitle: "Crea una cuenta para guardar tus historias.",
    email: "Correo electrónico",
    password: "Contraseña",
    passwordHint: "Al menos 6 caracteres",
    loginBtn: "Iniciar sesión",
    registerBtn: "Crear cuenta",
    loading: "Cargando...",
    noAccount: "¿No tienes cuenta? Crea una",
    hasAccount: "¿Ya tienes cuenta? Inicia sesión",
    forgotPassword: "¿Olvidaste tu contraseña?",
    resetSubtitle: "Ingresa tu correo para recibir un enlace de recuperación.",
    resetBtn: "Enviar enlace",
    resetLinkSent: "¡Correo enviado! Revisa tu bandeja y carpeta de spam.",
    logout: "Cerrar sesión",
    loggedInAs: "Sesión iniciada como",
    listening: "Escuchando...",
    tapToSpeak: "Toca para hablar",
    shareStory: "Compartir historia",
    shareSuccess: "Historia copiada al portapapeles",
    whenHappened: "¿Cuándo pasó esto? (Opcional)",
    datePlaceholder: "ej. 1985, Verano del '92, Cuando tenía 10...",
    inspireMe: "Inspirame",
    imagePrompt: "¿Qué te recuerda esto?",
    saving: "Guardando...",
    profileTitle: "Perfil",
    identity: "Identidad",
    experience: "Experiencia",
    collection: "Colección",
    exportCollection: "Exportar Colección",
    clearData: "Borrar Datos",
    signOut: "Cerrar Sesión",
    secureStoriesTitle: "Protege tus historias",
    secureStoriesBody: "Crea una cuenta para respaldar tu colección y acceder desde cualquier dispositivo.",
    guestMode: "MODO INVITADO",
    tapToName: "Toca para nombrar...",
    displayNameHint: "Este nombre aparecerá cuando compartas historias con tu familia.",
    resetConfirm: "¿Borrar todos los datos? Esta acción no se puede deshacer.",
    navHome: "Inicio",
    navStories: "Historias",
    navFamily: "Familia",
    navProfile: "Perfil",
    navNotifications: "Avisos",
    notificationsTitle: "Notificaciones",
    markAllRead: "Marcar leídas",
    noNotifications: "No hay notificaciones aún.",
    familyTitle: "Tu Familia",
    peopleOf: "Familia de",
    storiesTitle: "Tus Historias",
    noStories: "No hay historias aún.",
    writeFirstStory: "Escribir primera historia",
    chapter: "Capítulo",
    of: "de",
    inspiredBy: "Inspirado por ti",
    inspirationPrefix: "Algo como...",
    notificationSaw: "Alguien vio tu historia",
    notificationLike: "A alguien le gustó tu historia",
    notificationNew: "Alguien acaba de compartir una historia",
    support: "Ayuda y Comentarios",
    contactTitle: "Contáctanos",
    contactSubtitle: "¿Tienes una sugerencia o necesitas ayuda? Nos encantaría escucharte.",
    contactBtn: "Envíanos un correo",
  },
};

export const QUESTION_EXAMPLES = {
  en: {
    0: "I remember the sound of her laugh during Sunday dinners...", // q1: First memory
    1: "I want them to know she always put her family first…", // q2: What everyone should know
    2: "She is known for her incredible cherry pies...", // q3: Known for
    3: "Protective · Energetic · Devoted", // q4: One word description
    4: "Her family is everything to her...", // q5: Mattered most
  },
  es: {
    0: "Recuerdo el sonido de su risa durante las cenas del domingo...",
    1: "Quiero que sepan que siempre puso a su familia primero…",
    2: "Es conocida por sus increíbles pasteles de cereza...",
    3: "Protección · Energía · Compromiso",
    4: "Su familia lo es todo para ella...",
  }
};

export const LS = {
  people: "vms_people_v0",
  activePersonId: "vms_active_person_id_v0",
  questionState: "vms_weekly_question_state_v0",
  draftPrefix: "vms_draft_v0_",
  usedPrefix: "vms_used_questions_v0_",
  badgesPrefix: "vms_badges_v0_",
  lang: "vms_lang_v0",
};
